# Base configs
baseurl: "https://eunbee31.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Eun-Bee K."
subtitle: "See the world through my eyes!"
author: "Eun-Bee K."
header:
 title: "Photography"
 subtitle: "by Eun-Bee K."
footer:
 name: "Hey there, my name is Eun-Bee K."
 bio: "Hello!"
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  #facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/EunBeeKANG1"
  instagram: "https://www.instagram.com/lagaminebee"
  #dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/eun-bee-kang"
  github: "https://www.github.com/eunbee31"
